-- DROP TABLE IF EXISTS USERS;
-- DROP TABLE IF EXISTS MUTTERS;

CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    PASS VARCHAR(255) NOT NULL
);

CREATE TABLE MUTTERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    --時刻を自動で入れる
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    --いいねカウント
    LIKES_COUNT INT DEFAULT 0 NOT NULL
);